spring:
  application:
    name: todo-list
  datasource:
    url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
